//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Presets/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""fdcad6ba-b23a-468a-8c03-cc219814dc0c"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""5ecf0595-bbdd-4ea2-a8da-96fd12451966"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AltClick"",
                    ""type"": ""Button"",
                    ""id"": ""a0a64ed5-57e9-449e-b8cf-f1d8f352247e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""351b1599-68be-47ce-b60f-c23c23b0d616"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""ecc969de-58b3-4489-9434-fe8f960cf9ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""7c2c3190-9269-4463-9a42-9c59c04adf08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""a9048667-7142-4bad-ba50-7a63d85bb75b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickItem"",
                    ""type"": ""Button"",
                    ""id"": ""a36b86af-5b8a-46c9-a407-cd041e557db2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickGarbage"",
                    ""type"": ""Button"",
                    ""id"": ""ccafd9ce-a3f5-4cbc-bd30-575007418362"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""cf8824c6-a4af-4a5c-8e9d-ccfa940d481a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseWheel"",
                    ""type"": ""Button"",
                    ""id"": ""28207a3a-f9af-48a9-be2a-d1a1da7acc41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inv_selectSlot1"",
                    ""type"": ""Button"",
                    ""id"": ""c387c2af-7329-4093-86ee-ff4f3ddbf234"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inv_selectSlot2"",
                    ""type"": ""Button"",
                    ""id"": ""1daa091e-5870-4721-9200-09e9fe5a28c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inv_selectSlot3"",
                    ""type"": ""Button"",
                    ""id"": ""9c578794-5e69-4937-a0d4-89b317a03b78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inv_selectSlot4"",
                    ""type"": ""Button"",
                    ""id"": ""d6212f08-c808-498f-bc10-4c88556c3634"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inv_selectSlot5"",
                    ""type"": ""Button"",
                    ""id"": ""eb509fb2-b1c8-47b4-a061-01f71665c7f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inv_selectSlot6"",
                    ""type"": ""Button"",
                    ""id"": ""95067a2d-e576-4ed6-9833-92e375f196ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseShop"",
                    ""type"": ""Button"",
                    ""id"": ""8dab584d-98f3-4bc3-b106-ee3160e8b987"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""de2dbbd0-6740-4f19-a505-99792dfefb95"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC;Gamepad"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2672ac26-5b8f-4bfb-a853-46bae962fe7e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd8a96bc-895b-4033-88b6-1410863d94e5"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": ""PC;Gamepad"",
                    ""action"": ""AltClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e18dcb78-ce72-4887-b4e1-0eb814bd7305"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AltClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""326ebc78-f6b5-44d2-b672-f3402071220c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edf7213c-0bd2-4fcf-a7ca-4875bd06c41f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ebcd344-9973-43ad-8083-1cc0788bdae7"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db0317e7-b2ae-4603-aef7-941e18155064"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7438a767-eafe-4981-97fc-ee7d9cd624fa"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ef35855-02bd-4eac-8b7d-8dd197dc5d3c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""d45393c7-3b50-4214-8358-7a33a1610a0d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""fdb5586d-9975-4933-bded-3bd122fab13b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""36ccf16d-101d-489d-90fa-06693384b04f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""c63639e5-2844-4590-bfa0-c8ddddb73429"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""da77d61b-ed8e-40b1-93b2-9bd7de825954"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""54a74731-cdd9-40b8-bd74-69c0bf64166e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""81b527e7-4e82-4455-a908-626d7d233b66"",
                    ""path"": ""<Gamepad>/dpad/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cd87975-5e05-4d19-ac7c-7d1b41083e09"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40702413-c426-4a04-b9cd-b70dc1f5f36c"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b02aa857-25e5-4cc7-b3e8-6f2eefca3f8c"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""PickItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ac2caa2-6ce0-4bd8-a058-b808b2c8b6fd"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""PickGarbage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""MouseWheel"",
                    ""id"": ""06a02047-c0e8-4f79-962e-eebf1e089045"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseWheel"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c10722ca-40fa-4b1c-b0cc-7d6d165cfeaa"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MouseWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""91c4b6d5-028f-4a29-a432-3eeb9edd91b0"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MouseWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""95d81327-1382-48fe-9b9b-c37bda327ae2"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Inv_selectSlot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cd4a047-6ce3-48b2-8576-20fdbb629af9"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Inv_selectSlot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcd085db-c8ae-4d32-85c7-20dca22e4921"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Inv_selectSlot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f5daafd-6c7c-4ef1-9cf3-23c9a857e141"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Inv_selectSlot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9955743d-db04-457a-934b-4c37e33e4407"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Inv_selectSlot5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""416424a3-c9a7-4ca3-9b9e-4091626ff3c3"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Inv_selectSlot6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e69e4d24-783b-42bd-91a5-10b99ecfdb6d"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf5708f0-5b50-4124-b3bf-86b061e42c57"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""CloseShop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""1f498cf4-da71-447e-82ca-3f0f2b70a91d"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Click = m_Gameplay.FindAction("Click", throwIfNotFound: true);
        m_Gameplay_AltClick = m_Gameplay.FindAction("AltClick", throwIfNotFound: true);
        m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
        m_Gameplay_Jump = m_Gameplay.FindAction("Jump", throwIfNotFound: true);
        m_Gameplay_Run = m_Gameplay.FindAction("Run", throwIfNotFound: true);
        m_Gameplay_Crouch = m_Gameplay.FindAction("Crouch", throwIfNotFound: true);
        m_Gameplay_PickItem = m_Gameplay.FindAction("PickItem", throwIfNotFound: true);
        m_Gameplay_PickGarbage = m_Gameplay.FindAction("PickGarbage", throwIfNotFound: true);
        m_Gameplay_Dash = m_Gameplay.FindAction("Dash", throwIfNotFound: true);
        m_Gameplay_MouseWheel = m_Gameplay.FindAction("MouseWheel", throwIfNotFound: true);
        m_Gameplay_Inv_selectSlot1 = m_Gameplay.FindAction("Inv_selectSlot1", throwIfNotFound: true);
        m_Gameplay_Inv_selectSlot2 = m_Gameplay.FindAction("Inv_selectSlot2", throwIfNotFound: true);
        m_Gameplay_Inv_selectSlot3 = m_Gameplay.FindAction("Inv_selectSlot3", throwIfNotFound: true);
        m_Gameplay_Inv_selectSlot4 = m_Gameplay.FindAction("Inv_selectSlot4", throwIfNotFound: true);
        m_Gameplay_Inv_selectSlot5 = m_Gameplay.FindAction("Inv_selectSlot5", throwIfNotFound: true);
        m_Gameplay_Inv_selectSlot6 = m_Gameplay.FindAction("Inv_selectSlot6", throwIfNotFound: true);
        m_Gameplay_CloseShop = m_Gameplay.FindAction("CloseShop", throwIfNotFound: true);
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_Click;
    private readonly InputAction m_Gameplay_AltClick;
    private readonly InputAction m_Gameplay_Move;
    private readonly InputAction m_Gameplay_Jump;
    private readonly InputAction m_Gameplay_Run;
    private readonly InputAction m_Gameplay_Crouch;
    private readonly InputAction m_Gameplay_PickItem;
    private readonly InputAction m_Gameplay_PickGarbage;
    private readonly InputAction m_Gameplay_Dash;
    private readonly InputAction m_Gameplay_MouseWheel;
    private readonly InputAction m_Gameplay_Inv_selectSlot1;
    private readonly InputAction m_Gameplay_Inv_selectSlot2;
    private readonly InputAction m_Gameplay_Inv_selectSlot3;
    private readonly InputAction m_Gameplay_Inv_selectSlot4;
    private readonly InputAction m_Gameplay_Inv_selectSlot5;
    private readonly InputAction m_Gameplay_Inv_selectSlot6;
    private readonly InputAction m_Gameplay_CloseShop;
    public struct GameplayActions
    {
        private @Controls m_Wrapper;
        public GameplayActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_Gameplay_Click;
        public InputAction @AltClick => m_Wrapper.m_Gameplay_AltClick;
        public InputAction @Move => m_Wrapper.m_Gameplay_Move;
        public InputAction @Jump => m_Wrapper.m_Gameplay_Jump;
        public InputAction @Run => m_Wrapper.m_Gameplay_Run;
        public InputAction @Crouch => m_Wrapper.m_Gameplay_Crouch;
        public InputAction @PickItem => m_Wrapper.m_Gameplay_PickItem;
        public InputAction @PickGarbage => m_Wrapper.m_Gameplay_PickGarbage;
        public InputAction @Dash => m_Wrapper.m_Gameplay_Dash;
        public InputAction @MouseWheel => m_Wrapper.m_Gameplay_MouseWheel;
        public InputAction @Inv_selectSlot1 => m_Wrapper.m_Gameplay_Inv_selectSlot1;
        public InputAction @Inv_selectSlot2 => m_Wrapper.m_Gameplay_Inv_selectSlot2;
        public InputAction @Inv_selectSlot3 => m_Wrapper.m_Gameplay_Inv_selectSlot3;
        public InputAction @Inv_selectSlot4 => m_Wrapper.m_Gameplay_Inv_selectSlot4;
        public InputAction @Inv_selectSlot5 => m_Wrapper.m_Gameplay_Inv_selectSlot5;
        public InputAction @Inv_selectSlot6 => m_Wrapper.m_Gameplay_Inv_selectSlot6;
        public InputAction @CloseShop => m_Wrapper.m_Gameplay_CloseShop;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @Click.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnClick;
                @AltClick.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAltClick;
                @AltClick.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAltClick;
                @AltClick.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAltClick;
                @Move.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @Run.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRun;
                @Crouch.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCrouch;
                @PickItem.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPickItem;
                @PickItem.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPickItem;
                @PickItem.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPickItem;
                @PickGarbage.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPickGarbage;
                @PickGarbage.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPickGarbage;
                @PickGarbage.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPickGarbage;
                @Dash.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDash;
                @MouseWheel.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMouseWheel;
                @MouseWheel.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMouseWheel;
                @MouseWheel.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMouseWheel;
                @Inv_selectSlot1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot1;
                @Inv_selectSlot1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot1;
                @Inv_selectSlot1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot1;
                @Inv_selectSlot2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot2;
                @Inv_selectSlot2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot2;
                @Inv_selectSlot2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot2;
                @Inv_selectSlot3.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot3;
                @Inv_selectSlot3.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot3;
                @Inv_selectSlot3.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot3;
                @Inv_selectSlot4.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot4;
                @Inv_selectSlot4.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot4;
                @Inv_selectSlot4.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot4;
                @Inv_selectSlot5.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot5;
                @Inv_selectSlot5.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot5;
                @Inv_selectSlot5.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot5;
                @Inv_selectSlot6.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot6;
                @Inv_selectSlot6.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot6;
                @Inv_selectSlot6.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInv_selectSlot6;
                @CloseShop.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCloseShop;
                @CloseShop.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCloseShop;
                @CloseShop.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCloseShop;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @AltClick.started += instance.OnAltClick;
                @AltClick.performed += instance.OnAltClick;
                @AltClick.canceled += instance.OnAltClick;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @PickItem.started += instance.OnPickItem;
                @PickItem.performed += instance.OnPickItem;
                @PickItem.canceled += instance.OnPickItem;
                @PickGarbage.started += instance.OnPickGarbage;
                @PickGarbage.performed += instance.OnPickGarbage;
                @PickGarbage.canceled += instance.OnPickGarbage;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @MouseWheel.started += instance.OnMouseWheel;
                @MouseWheel.performed += instance.OnMouseWheel;
                @MouseWheel.canceled += instance.OnMouseWheel;
                @Inv_selectSlot1.started += instance.OnInv_selectSlot1;
                @Inv_selectSlot1.performed += instance.OnInv_selectSlot1;
                @Inv_selectSlot1.canceled += instance.OnInv_selectSlot1;
                @Inv_selectSlot2.started += instance.OnInv_selectSlot2;
                @Inv_selectSlot2.performed += instance.OnInv_selectSlot2;
                @Inv_selectSlot2.canceled += instance.OnInv_selectSlot2;
                @Inv_selectSlot3.started += instance.OnInv_selectSlot3;
                @Inv_selectSlot3.performed += instance.OnInv_selectSlot3;
                @Inv_selectSlot3.canceled += instance.OnInv_selectSlot3;
                @Inv_selectSlot4.started += instance.OnInv_selectSlot4;
                @Inv_selectSlot4.performed += instance.OnInv_selectSlot4;
                @Inv_selectSlot4.canceled += instance.OnInv_selectSlot4;
                @Inv_selectSlot5.started += instance.OnInv_selectSlot5;
                @Inv_selectSlot5.performed += instance.OnInv_selectSlot5;
                @Inv_selectSlot5.canceled += instance.OnInv_selectSlot5;
                @Inv_selectSlot6.started += instance.OnInv_selectSlot6;
                @Inv_selectSlot6.performed += instance.OnInv_selectSlot6;
                @Inv_selectSlot6.canceled += instance.OnInv_selectSlot6;
                @CloseShop.started += instance.OnCloseShop;
                @CloseShop.performed += instance.OnCloseShop;
                @CloseShop.canceled += instance.OnCloseShop;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // Menu
    private readonly InputActionMap m_Menu;
    private IMenuActions m_MenuActionsCallbackInterface;
    public struct MenuActions
    {
        private @Controls m_Wrapper;
        public MenuActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void SetCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterface != null)
            {
            }
            m_Wrapper.m_MenuActionsCallbackInterface = instance;
            if (instance != null)
            {
            }
        }
    }
    public MenuActions @Menu => new MenuActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IGameplayActions
    {
        void OnClick(InputAction.CallbackContext context);
        void OnAltClick(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnPickItem(InputAction.CallbackContext context);
        void OnPickGarbage(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnMouseWheel(InputAction.CallbackContext context);
        void OnInv_selectSlot1(InputAction.CallbackContext context);
        void OnInv_selectSlot2(InputAction.CallbackContext context);
        void OnInv_selectSlot3(InputAction.CallbackContext context);
        void OnInv_selectSlot4(InputAction.CallbackContext context);
        void OnInv_selectSlot5(InputAction.CallbackContext context);
        void OnInv_selectSlot6(InputAction.CallbackContext context);
        void OnCloseShop(InputAction.CallbackContext context);
    }
    public interface IMenuActions
    {
    }
}
